### ISSUE TITLE
Framework Ideas

### ISSUE THREAD

**Issue by zeyla** [zeyla/serenity.rs#6]
Right now it's mostly a command parser (<https://raw.githubusercontent.com/zeyla/serenity.rs/feb2ee1eddc92cf02fc9e64534030ae0d374418b/examples/06_command_framework.rs>), but a full framework is the end goal.

Basically an issue for tracking ideas.

Current function signature: `fn weather(context: Context, message: Message, arguments: Vec<String>)`

### Named parameters

Status: **Done ✓**

Rather than the current signature, allow `fn weather(context: Context, message: Message, location: String, action: Option<String>)`

### Struct parameters

Status: **Done ✓** #36 

Possibly something like

```rs
#[derive(Deserialize)]
struct WeatherArguments {
    pub action: Option<String>,
    pub location: String,
}

fn weather(context: Context, message: Message, arguments: WeatherArguments)
```

### Pre-/Post-Command Closures

Status: **Done ✓** #13 
Closures that can run before or after command execution (not specific to a command). Idea courtesy @fwrs 

### Help Command

Status: **Done ✓** #40

### Multiple Prefixes

Status: **Done ✓** #38

**Comment by fwrs** [comment]
Default help command which shows the list of commands (probably also doing all checks so only available commands appear) and information for specific ones if arguments are given. It has default layout which can be customized by user inside `framework.configure` with a closure.
This also means that a way to set bot description is needed.

**Comment by fwrs** [comment]
Multiple Prefixes and Help Command are now done

**Comment by zeyla** [comment]
The framework is at a state where it is feature-complete enough for v0.1.2 soon
