### ISSUE TITLE
MessageBuilder unsafe content

### ISSUE THREAD

**Issue by fwrs** [zeyla/serenity.rs#7]
* by default message builder should escape all mentions as there's `mention` function
* add push_unsafe method that ensures that user input doesn't cause unwanted results such as formatting, mention spam, everyone/here, custom emojis etc
* add push_italic, push_italic_unsafe, push_mono, push_mono_unsafe, push_bold, push_bold_unsafe, push_codeblock, push_codeblock_unsafe. because in different contexts normalizing is different (eg in inline monospace you shouldn't escape bold formatting)
* also put normalize methods in context I guess so message builder isn't mandatory

**Comment by zeyla** [comment]
Closed by #12

**Comment by fwrs** [comment]
🏃
